server:
  port: 8080

spring:
    application:
      name: gateway-server

---
spring:
  profiles: dev
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://localhost:8081/
          predicates:
            - Path=/v1/restaurants/**
        - id: user-service
          uri: http://localhost:8082/
          predicates:
            - Path=/v1/users/**
        - id: booking-service
          uri: http://localhost:8083/
          predicates:
            - Path=/v1/bookings/**

---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: http://restaurant:4431/
          predicates:
            - Path=/v1/restaurants/**
        - id: user-service
          uri: http://user:8082/
          predicates:
            - Path=/v1/users/**
        - id: booking-service
          uri: http://booking:8082/
          predicates:
            - Path=/v1/bookings/**