server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/v1/restaurants/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/users/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/v1/bookings/**

---
sprint:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/