version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - checkout
      - restore_cache:
          keys:
            - mvn-dependencies-{{ checksum "pom.xml" }}
            - mvn-dependencies-
      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: mvn-dependencies-{{ checksum "pom.xml" }}
      - run: mvn jacoco:report-aggregate
      - run: "bash <(curl -s https://codecov.io/bash)"