version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    working_directory: ~/estiasi
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn install
      - run: mvn test
      - run: mvn jacoco:report-aggregate
      - run: "bash <(curl -s https://codecov.io/bash)"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-