version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-
      - run: ls -la ~/.m2/repository/
      - run: pwd
      - run: mvn -pl gateway-server -am clean install
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-
      - run: mvn jacoco:report-aggregate
      - run: "bash <(curl -s https://codecov.io/bash)"