spring:
  application:
    name: restaurant-service
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:estiasi
    driverClassName: org.h2.Driver
    usernname: root
    password:

---
spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
      url: jdbc:mysql://mysql:3306/estiasi
      driverClassName: com.mysql.cj.jdbc.Driver
      usernname: root
      password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
